config/routes.rb
Rails.application.routes.draw do
  post 'purchase' => 'purchases#create'

  root 'vehicles#index'

  get 'vehicles' => 'vehicles#index'

  get 'vehicle' => 'vehicles#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def create
    @vehicles = ActiveSupport::JSON.decode params[:vehicles]
    @name = purchase_params[:name]
    @model = @vehicles[@name]['model']
    @manufacturer = @vehicles[@name]['manufacturer']
    @cost = @vehicles[@name]['cost'].to_i
    check_credits
  end

  private
    def purchase_params
      params.require(:purchase).permit(:name)
    end

    def check_credits
      if session['credits'] < @cost
        flash[:danger] = "Insufficient credits."
        @credits = session['credits']
        render 'vehicles/index'
      else
        @purchase = Purchase.new(name: @name,
                                 model: @model,
                                 manufacturer: @manufacturer,
                                 cost: @cost)
        save_purchase
        render 'vehicles/index'
      end
    end

    def save_purchase
      if @purchase.save
        flash.now[:success] = "Purchase successful."
        session['credits'] -= @cost
        @credits = session['credits']
      else
        flash.now[:danger] = "Error in purchase!"
      end
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  class SwapiInterface
    #Equivalent to class.extend(HTTParty)
    include HTTParty
    
    class << self

      VEHICLES_URI = ENV['TARGET_URI']

      def get_request(page=1)
        get(VEHICLES_URI, query: { page: page })
      end

      def all_vehicles
        vehicles = {}
        curr = get(VEHICLES_URI)
        until curr['next'].nil?
          curr['results'].each do |result|
            vehicles[result['name']] = { 'model' => result['model'],
                                         'manufacturer' => result['manufacturer'],
                                         'cost' => result['cost_in_credits'] }
          end
          curr = get(curr['next'])
        end
        vehicles
      end

    end

  end

  def index
    if params[:vehicles]
      @vehicles = ActiveSupport::JSON.decode(params[:vehicles])
    else
      @vehicles = SwapiInterface.all_vehicles
    end
    @credits = session['credits'] ||= 1000000
  end

  def show
    name = params[:vehicle]
    @vehicles = ActiveSupport::JSON.decode params[:vehicles]
    @vehicle = { name: name,
                 model: @vehicles[name]['model'],
                 manufacturer: @vehicles[name]['manufacturer'],
                 cost: @vehicles[name]['cost'] }
    render :show
  end

  private
    def option_param
      params.require(:vehicles).permit(:option)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpaceMax</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <% flash.each do |k,v| %>
      <%= v %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to "All Vehicles", vehicles_path %></li>
  </ul>
</nav>

app/views/vehicles/index.html.erb
<h1>Welcome to SpaceMax! The friendliest dealership in the galaxy!</h1>

<!-- Get all vehicles. -->

<h3>You have <%= @credits %> credits left.</h3>
<% if @purchase %>
  <%= content_tag(:h3, "Your last purchase costs #{@cost} credits") %>
<% end %>

<h1>See Vehicle</h1>
<form action="<%= vehicle_path %>" method="get">
  <%= select_tag "vehicle", options_for_select(@vehicles, 'name') %>
  <input type="hidden" name="vehicles" value="<%= ActiveSupport::JSON.encode @vehicles %>">
  <input type="submit" value="Submit">
</form>

<h1>Purchase Vehicle</h1>
<form action="<%= purchase_path %>" method="post">
  <%= select_tag "purchase[name]", options_for_select(@vehicles, 'name') %>
  <input type="hidden" name="vehicles" value="<%= ActiveSupport::JSON.encode @vehicles %>">
  <input type="submit" value="Submit">
  <!-- Auth Token necessary for post requests. -->
  <input type="hidden" name="authenticity_token"  value="<%= form_authenticity_token %>">
</form>

app/views/vehicles/show.html.erb
<input type="hidden" name="vehicles" value="<%= ActiveSupport::JSON.encode @vehicles %>">

<h1>Vehicles#show</h1>
<p><%= "You selected the #{@vehicle[:name]}, model #{@vehicle[:model]}." %><br>
<%= "It costs #{@vehicle[:cost]} credits." %><br>
<%= "It was manufactured by #{@vehicle[:manufacturer]}." %></p>

<form action="<%= purchase_path %>" method="post">
  <input type="hidden" name="vehicles" value="<%= ActiveSupport::JSON.encode @vehicles %>">
  <input type="hidden" name="purchase[name]" value="<%= @vehicle[:name] %>">
  <!-- Auth Token necessary for post requests. -->
  <input type="hidden" name="authenticity_token"  value="<%= form_authenticity_token %>">
  <input type="submit" value="Buy it">
</form> 